[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 20000
via_ir = true

[rpc_endpoints]
bsc_testnet = "https://bsc-testnet-rpc.publicnode.com"
bsc = "https://bsc-rpc.publicnode.com"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
